name: domain
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.13.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  rxdart: ^0.28.0
  logger: ^2.5.0
  worker_manager: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^4.0.1
  build_runner: ^2.16.1
